## Naive Bayes Classifier

In [1]:
import pandas as pd
from sklearn import datasets
wine=datasets.load_wine()
wine

{'data': array([[1.423e+01, 1.710e+00, 2.430e+00, ..., 1.040e+00, 3.920e+00,
         1.065e+03],
        [1.320e+01, 1.780e+00, 2.140e+00, ..., 1.050e+00, 3.400e+00,
         1.050e+03],
        [1.316e+01, 2.360e+00, 2.670e+00, ..., 1.030e+00, 3.170e+00,
         1.185e+03],
        ...,
        [1.327e+01, 4.280e+00, 2.260e+00, ..., 5.900e-01, 1.560e+00,
         8.350e+02],
        [1.317e+01, 2.590e+00, 2.370e+00, ..., 6.000e-01, 1.620e+00,
         8.400e+02],
        [1.413e+01, 4.100e+00, 2.740e+00, ..., 6.100e-01, 1.600e+00,
         5.600e+02]]),
 'target': array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1

In [5]:
data=pd.DataFrame(wine.data,columns=wine.feature_names)
data.head()

alcohol  malic_acid   ash  alcalinity_of_ash  magnesium  total_phenols  \
0    14.23        1.71  2.43               15.6      127.0           2.80   
1    13.20        1.78  2.14               11.2      100.0           2.65   
2    13.16        2.36  2.67               18.6      101.0           2.80   
3    14.37        1.95  2.50               16.8      113.0           3.85   
4    13.24        2.59  2.87               21.0      118.0           2.80   

   flavanoids  nonflavanoid_phenols  proanthocyanins  color_intensity   hue  \
0        3.06                  0.28             2.29             5.64  1.04   
1        2.76                  0.26             1.28             4.38  1.05   
2        3.24                  0.30             2.81             5.68  1.03   
3        3.49                  0.24             2.18             7.80  0.86   
4        2.69                  0.39             1.82             4.32  1.04   

   od280/od315_of_diluted_wines  proline  
0                          3.92   1065.0  
1                          3.40   1050.0  
2                          3.17   1185.0  
3                          3.45   1480.0  
4                          2.93    735.0

In [9]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(wine.data,wine.target,test_size=0.30,random_state=2)

In [11]:
from sklearn.naive_bayes import GaussianNB
gnb=GaussianNB()
gnb.fit(x_train,y_train)
y_pred=gnb.predict(x_test)
y_pred

array([0, 0, 2, 1, 0, 0, 1, 2, 1, 0, 1, 0, 0, 2, 2, 1, 0, 0, 0, 2, 1, 0,
       1, 1, 0, 0, 1, 0, 0, 0, 2, 1, 2, 2, 0, 1, 2, 1, 1, 1, 2, 2, 1, 0,
       2, 1, 1, 0, 2, 1, 1, 1, 1, 1])

In [12]:
from sklearn.model_selection import cross_val_score
from sklearn.metrics import classification_report,confusion_matrix
print("==confusion Matrix==>")
conff=confusion_matrix(y_test,y_pred)
print(conff)
print("\n")
c=print(conff[0,1]+conff[1,0])#FP(false+ve) and FN(False-ve)
print(conff[0,0]+conff[1,1])#True +ve and True _ve
from sklearn.metrics import accuracy_score
print("Acuuracy:",accuracy_score(y_test,y_pred)*100)


==confusion Matrix==>
[[19  1  0]
 [ 0 20  0]
 [ 0  1 13]]


1
39
Acuuracy: 96.29629629629629


## K nearest neighbours


In [13]:
import pandas as pd
d=pd.Series([158,158,158,160,160,163,163,160,163,165,165,165,168,168,168,170,170,170])
d1=pd.Series([58,59,63,59,60,60,61,64,64,61,62,65,62,63,66,63,64,68])
a=pd.DataFrame({'d':d,'d1':d1})
p=161
q=61
a["dis"]=(((p-a['d'])**2)+((q-a['d1'])**2))**0.5
a["target"]=['M','M','M','M','M','M','M','M','L','L','L','L','L','L','L','L','L','L']
a

d  d1        dis target
0   158  58   4.242641      M
1   158  59   3.605551      M
2   158  63   3.605551      M
3   160  59   2.236068      M
4   160  60   1.414214      M
5   163  60   2.236068      M
6   163  61   2.000000      M
7   160  64   3.162278      M
8   163  64   3.605551      L
9   165  61   4.000000      L
10  165  62   4.123106      L
11  165  65   5.656854      L
12  168  62   7.071068      L
13  168  63   7.280110      L
14  168  66   8.602325      L
15  170  63   9.219544      L
16  170  64   9.486833      L
17  170  68  11.401754      L

In [12]:
x=a.drop(["target","dis"],axis=1).values
y=a["target"].values
from sklearn.preprocessing import LabelEncoder
labelencoder_y=LabelEncoder()
y=labelencoder_y.fit_transform(y)
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=1)
#print(x_train)
from sklearn.neighbors import KNeighborsClassifier
#knn=KNeighborsClassifier()
knn=KNeighborsClassifier(n_neighbors=1)
knn.fit(x_train,y_train)
y_pred=knn.predict(x_test)
y_pred
knn.predict([[170,63]])
from sklearn import metrics
print("accuracy:",metrics.accuracy_score(y_test,y_pred))


accuracy: 1.0


In [25]:
import numpy as np
import pandas as pd
data=pd.read_csv("bird.csv")
data.drop("id",axis=1,inplace=True)
data.head()

huml  humw  ulnal  ulnaw   feml  femw   tibl  tibw   tarl  tarw type
0  80.78  6.68  72.01   4.88  41.81  3.70   5.50  4.03  38.70  3.84   SW
1  88.91  6.63  80.53   5.59  47.04  4.30  80.22  4.51  41.50  4.01   SW
2  79.97  6.37  69.26   5.28  43.07  3.90  75.35  4.04  38.31  3.34   SW
3  77.65  5.70  65.76   4.77  40.04  3.52  69.17  3.40  35.78  3.41   SW
4  62.80  4.84  52.09   3.73  33.95  2.72  56.27  2.96  31.88  3.13   SW

In [33]:
x=data.drop('type',axis=1)
y=data['type']
x.loc[:,:].replace(np.NaN,0,inplace=True)
#x.isnull().sum()

In [35]:
from sklearn.preprocessing import LabelEncoder
labelencoder_y=LabelEncoder()
y=labelencoder_y.fit_transform(y)

In [80]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.30,random_state=42)

In [81]:
from sklearn.ensemble import RandomForestClassifier
rfc=RandomForestClassifier()
rfc.fit(x_train,y_train)
#predictions
rfc_predict=rfc.predict(x_test)
rfc_predict

C:\Users\APSSDC\Anaconda3\lib\site-packages\sklearn\ensemble\forest.py:245: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)


array([5, 2, 5, 2, 2, 5, 3, 0, 1, 5, 5, 3, 2, 3, 2, 2, 1, 1, 4, 1, 4, 1,
       2, 1, 2, 2, 3, 2, 0, 0, 2, 3, 1, 4, 2, 3, 1, 3, 5, 0, 3, 3, 2, 3,
       3, 2, 3, 2, 2, 3, 0, 2, 3, 3, 2, 0, 0, 0, 3, 3, 2, 3, 3, 2, 3, 2,
       0, 3, 2, 2, 0, 2, 1, 0, 3, 1, 0, 3, 2, 2, 3, 2, 3, 3, 3, 3, 3, 3,
       0, 2, 2, 5, 1, 1, 1, 3, 3, 0, 2, 2, 4, 3, 2, 1, 2, 3, 3, 2, 3, 2,
       5, 3, 3, 2, 2, 5, 2, 2, 2, 3, 3, 4, 2, 3, 3, 2], dtype=int32)

In [83]:
#evaluating performance
#from sklearn.model_selection import cross_val_score
#from sklearn.metrics import classification_report,confusion_matrix,accuracy_score


In [77]:
from sklearn.metrics import accuracy_score
print("Acuuracy:",accuracy_score(y_test,rfc_predict)*100)

Acuuracy: 80.95238095238095


In [78]:
from sklearn.linear_model import LogisticRegression
a=LogisticRegression()
a.fit(x_train,y_train)
b=a.predict(x_test)
b

C:\Users\APSSDC\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
C:\Users\APSSDC\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:469: FutureWarning: Default multi_class will be changed to 'auto' in 0.22. Specify the multi_class option to silence this warning.
  "this warning.", FutureWarning)


array([5, 2, 5, 2, 2, 3, 3, 3, 3, 3, 3, 3, 2, 3, 2, 2, 3, 1, 4, 0, 4, 1,
       2, 1, 2, 2, 3, 2, 5, 3, 2, 5, 2, 1, 2, 4, 1, 3, 5, 0, 3, 3, 2, 3,
       3, 2, 5, 2, 2, 3, 3, 2, 4, 3, 2, 0, 0, 0, 3, 3, 2, 3, 3, 2, 5, 2,
       0, 3, 5, 2, 5, 2, 2, 5, 3, 3, 0, 5, 2, 2, 3, 2, 3, 3, 3, 3, 3, 3,
       0, 2, 2, 5, 1, 4, 2, 1, 3, 0, 2, 2, 1, 3, 2, 1, 2, 3, 3, 2, 3, 4,
       5, 3, 3, 2, 2, 1, 2, 2, 2, 3, 3, 4, 2, 3, 3, 2], dtype=int32)

In [79]:
from sklearn.metrics import accuracy_score
print("Acuuracy:",accuracy_score(y_test,b)*100)

Acuuracy: 87.3015873015873
