In [1]:
#datetime
import datetime

In [2]:
d=datetime.datetime.now()
d

datetime.datetime(2019, 11, 21, 9, 52, 16, 809511)

In [3]:
d.year


2019

In [4]:
d.month

11

In [5]:
d.minute


52

In [6]:
d.hour

9

In [7]:
d.second

16

In [8]:
d.microsecond

809511

In [9]:
import calendar

In [10]:
calendar.month(2019,11)

'   November 2019\nMo Tu We Th Fr Sa Su\n             1  2  3\n 4  5  6  7  8  9 10\n11 12 13 14 15 16 17\n18 19 20 21 22 23 24\n25 26 27 28 29 30\n'

In [14]:
cal=calendar.month(2020,2)

In [12]:
cal

'     April 2020\nMo Tu We Th Fr Sa Su\n       1  2  3  4  5\n 6  7  8  9 10 11 12\n13 14 15 16 17 18 19\n20 21 22 23 24 25 26\n27 28 29 30\n'

In [15]:
print(cal)

   February 2020
Mo Tu We Th Fr Sa Su
                1  2
 3  4  5  6  7  8  9
10 11 12 13 14 15 16
17 18 19 20 21 22 23
24 25 26 27 28 29



In [17]:
help(calendar.HTMLCalendar)

Help on class HTMLCalendar in module calendar:

class HTMLCalendar(Calendar)
 |  HTMLCalendar(firstweekday=0)
 |  
 |  This calendar returns complete HTML pages.
 |  
 |  Method resolution order:
 |      HTMLCalendar
 |      Calendar
 |      builtins.object
 |  
 |  Methods defined here:
 |  
 |  formatday(self, day, weekday)
 |      Return a day as a table cell.
 |  
 |  formatmonth(self, theyear, themonth, withyear=True)
 |      Return a formatted month as a table.
 |  
 |  formatmonthname(self, theyear, themonth, withyear=True)
 |      Return a month name as a table row.
 |  
 |  formatweek(self, theweek)
 |      Return a complete week as a table row.
 |  
 |  formatweekday(self, day)
 |      Return a weekday name as a table header.
 |  
 |  formatweekheader(self)
 |      Return a header for a week as a table row.
 |  
 |  formatyear(self, theyear, width=3)
 |      Return a formatted year as a table of tables.
 |  
 |  formatyearpage(self, theyear, width=3, css='calendar.css', encod

In [21]:
dir(calendar)

['Calendar',
 'EPOCH',
 'FRIDAY',
 'February',
 'HTMLCalendar',
 'IllegalMonthError',
 'IllegalWeekdayError',
 'January',
 'LocaleHTMLCalendar',
 'LocaleTextCalendar',
 'MONDAY',
 'SATURDAY',
 'SUNDAY',
 'THURSDAY',
 'TUESDAY',
 'TextCalendar',
 'WEDNESDAY',
 '_EPOCH_ORD',
 '__all__',
 '__builtins__',
 '__cached__',
 '__doc__',
 '__file__',
 '__loader__',
 '__name__',
 '__package__',
 '__spec__',
 '_colwidth',
 '_locale',
 '_localized_day',
 '_localized_month',
 '_spacing',
 'c',
 'calendar',
 'datetime',
 'day_abbr',
 'day_name',
 'different_locale',
 'error',
 'firstweekday',
 'format',
 'formatstring',
 'isleap',
 'leapdays',
 'main',
 'mdays',
 'month',
 'month_abbr',
 'month_name',
 'monthcalendar',
 'monthlen',
 'monthrange',
 'nextmonth',
 'prcal',
 'prevmonth',
 'prmonth',
 'prweek',
 'repeat',
 'setfirstweekday',
 'sys',
 'timegm',
 'week',
 'weekday',
 'weekheader']

In [22]:
calendar.prcal(2019)

                                  2019

      January                   February                   March
Mo Tu We Th Fr Sa Su      Mo Tu We Th Fr Sa Su      Mo Tu We Th Fr Sa Su
    1  2  3  4  5  6                   1  2  3                   1  2  3
 7  8  9 10 11 12 13       4  5  6  7  8  9 10       4  5  6  7  8  9 10
14 15 16 17 18 19 20      11 12 13 14 15 16 17      11 12 13 14 15 16 17
21 22 23 24 25 26 27      18 19 20 21 22 23 24      18 19 20 21 22 23 24
28 29 30 31               25 26 27 28               25 26 27 28 29 30 31

       April                      May                       June
Mo Tu We Th Fr Sa Su      Mo Tu We Th Fr Sa Su      Mo Tu We Th Fr Sa Su
 1  2  3  4  5  6  7             1  2  3  4  5                      1  2
 8  9 10 11 12 13 14       6  7  8  9 10 11 12       3  4  5  6  7  8  9
15 16 17 18 19 20 21      13 14 15 16 17 18 19      10 11 12 13 14 15 16
22 23 24 25 26 27 28      20 21 22 23 24 25 26      17 18 19 20 21 22 23
29 30                     

In [23]:
import tkinter as tk 
r = tk.Tk() 
r.title('Counting Seconds') 
button = tk.Button(r, text='Stop', width=25, command=r.destroy) 
button.pack() 
r.mainloop() 

### Numpy
* Numerical python

In [27]:
import numpy as np
a=np.random.randn(2,3)


In [28]:
a*a

array([[3.32662612, 0.10128745, 1.33707678],
       [0.44473556, 3.79780649, 0.63833663]])

In [29]:
a+a

array([[-3.64780817, -0.63651377, -2.31264072],
       [ 1.33376994,  3.89759233,  1.59791943]])

In [43]:
b=np.random.randn(3,4)
c=np.random.rand(1,10)
print(c)
b

[[0.99670295 0.03950885 0.63035272 0.00440001 0.08854165 0.1943288
  0.94816709 0.86841768 0.51128583 0.92132953]]


array([[ 0.23113682,  0.416104  ,  1.23875459, -1.12524008],
       [-1.20506298,  1.88367064, -0.27528482, -0.01804855],
       [ 0.61205229,  0.90085654, -0.68700454, -1.00702626]])

In [45]:
names=np.array([2,3,4,5,5])
names

array([2, 3, 4, 5, 5])

In [48]:
data=np.random.randn(5,10)
data

array([[-1.19547174, -3.02374319,  0.97081095,  0.85295927, -1.45291959,
         0.2884274 ,  0.17272132, -0.56739272, -1.5664229 , -0.57181158],
       [-1.44149991, -0.96414368,  0.81024316, -0.23984967,  2.56525674,
         0.17556181, -0.1520715 ,  0.6289468 , -0.53117837,  1.41760419],
       [ 2.23803522, -0.6614986 ,  1.42290404,  1.28815244,  1.55135267,
        -0.24189632,  1.40653752, -0.55505423, -0.34462724,  0.5317627 ],
       [-0.11099872, -1.66588309,  0.05715266, -0.89968906,  1.73011437,
        -0.44235553,  1.00058634, -1.30775334, -0.30924629, -0.72597361],
       [ 0.25630911,  0.34176608, -0.84225378,  0.0311106 ,  0.00465794,
         0.04432522,  0.22195305, -2.14351069,  0.39836502,  0.74223068]])

In [50]:
names==5

array([False, False, False,  True,  True])

In [53]:
data[0:,names==5]

IndexError: boolean index did not match indexed array along dimension 1; dimension is 10 but corresponding boolean dimension is 5

In [54]:
data[names==5]=0

In [55]:
data

array([[-1.19547174, -3.02374319,  0.97081095,  0.85295927, -1.45291959,
         0.2884274 ,  0.17272132, -0.56739272, -1.5664229 , -0.57181158],
       [-1.44149991, -0.96414368,  0.81024316, -0.23984967,  2.56525674,
         0.17556181, -0.1520715 ,  0.6289468 , -0.53117837,  1.41760419],
       [ 2.23803522, -0.6614986 ,  1.42290404,  1.28815244,  1.55135267,
        -0.24189632,  1.40653752, -0.55505423, -0.34462724,  0.5317627 ],
       [ 0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
         0.        ,  0.        ,  0.        ,  0.        ,  0.        ],
       [ 0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
         0.        ,  0.        ,  0.        ,  0.        ,  0.        ]])

In [57]:
(names==2)|(names==3)

array([ True,  True, False, False, False])

In [60]:
data[names!=2]=90

data

array([[-1.19547174, -3.02374319,  0.97081095,  0.85295927, -1.45291959,
         0.2884274 ,  0.17272132, -0.56739272, -1.5664229 , -0.57181158],
       [90.        , 90.        , 90.        , 90.        , 90.        ,
        90.        , 90.        , 90.        , 90.        , 90.        ],
       [90.        , 90.        , 90.        , 90.        , 90.        ,
        90.        , 90.        , 90.        , 90.        , 90.        ],
       [90.        , 90.        , 90.        , 90.        , 90.        ,
        90.        , 90.        , 90.        , 90.        , 90.        ],
       [90.        , 90.        , 90.        , 90.        , 90.        ,
        90.        , 90.        , 90.        , 90.        , 90.        ]])

In [67]:
a=np.empty((8,4))
for i in range(8):
    a[i]=i+1
a

array([[1., 1., 1., 1.],
       [2., 2., 2., 2.],
       [3., 3., 3., 3.],
       [4., 4., 4., 4.],
       [5., 5., 5., 5.],
       [6., 6., 6., 6.],
       [7., 7., 7., 7.],
       [8., 8., 8., 8.]])

In [69]:
a=np.random.randn(8,4)
a

array([[ 0.29870424, -0.87209982, -1.17758351, -0.84827812],
       [-0.75047038, -0.92909879, -2.06198072,  0.54436547],
       [ 0.32129057, -0.39414979, -1.15064999,  0.94966702],
       [-0.5969746 , -0.62829162, -1.3464301 ,  0.77874969],
       [ 0.32035157, -0.52213018,  1.23314295, -0.9936268 ],
       [-0.09847195, -0.16915804, -1.1867871 ,  0.74743382],
       [-2.2169207 ,  0.66571138, -2.05920076,  0.42885388],
       [ 1.49625314,  0.00669484,  0.68920371, -0.54851481]])

In [71]:
a[[2,3,7]]

array([[ 0.32129057, -0.39414979, -1.15064999,  0.94966702],
       [-0.5969746 , -0.62829162, -1.3464301 ,  0.77874969],
       [ 1.49625314,  0.00669484,  0.68920371, -0.54851481]])

In [70]:
a[[2,3,7]][:,1:3]

array([[-0.39414979, -1.15064999],
       [-0.62829162, -1.3464301 ],
       [ 0.00669484,  0.68920371]])

In [73]:
a=np.arange(16).reshape(2,2,4)  #2 matrices,2 rows ,4 col
a

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]]])

In [76]:
a.transpose((0,1,2))

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]]])

In [75]:
a.transpose((2,0,1))     

array([[[ 0,  4],
        [ 8, 12]],

       [[ 1,  5],
        [ 9, 13]],

       [[ 2,  6],
        [10, 14]],

       [[ 3,  7],
        [11, 15]]])

In [77]:
a.transpose(1,0,2)

array([[[ 0,  1,  2,  3],
        [ 8,  9, 10, 11]],

       [[ 4,  5,  6,  7],
        [12, 13, 14, 15]]])

In [78]:
### Pandas

In [79]:
#### Series
import pandas as pd
obj=pd.Series([4,7,-5,3])

In [80]:
obj

0    4
1    7
2   -5
3    3
dtype: int64

In [81]:
obj.index

RangeIndex(start=0, stop=4, step=1)

In [83]:
obj.values

array([ 4,  7, -5,  3], dtype=int64)

In [86]:
obj=pd.Series([4,7,-5,3],index=["d","c","e","f"])
obj

d    4
c    7
e   -5
f    3
dtype: int64

In [89]:
obj[2]


-5