#### Numpy library
-Processing N Dimensional arrays<br>
-numpy stores only homogeneous data


In [1]:
import numpy as np
li=[1,2,3]
a=np.array(li)
a
type(a)

numpy.ndarray

In [3]:
b=np.arange(15)
b

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [8]:
rn=np.random.randint(0,100,size=(3,3,3))
rn

array([[[76, 23, 35],
        [17,  7, 42],
        [99, 42, 35]],

       [[51, 85, 26],
        [60, 72,  7],
        [74,  7, 75]],

       [[ 5,  4, 23],
        [11, 84, 79],
        [17, 37, 95]]])

In [10]:
rn.ndim

3

In [11]:
rn.size

27

In [12]:
rn.shape

(3, 3, 3)

In [13]:
rn.dtype

dtype('int32')

In [14]:
rn.itemsize

4

In [15]:
rn.nbytes

108

### Pandas
-Data Cleaning<br>
-Data Transformation<br>
-Data Analysis<br>
##### Notations
-Series
-DataFrames

#series represents one dimensional data
#data frames represents the multidimensional data


In [3]:
import pandas as pd
internal1={'s1':21,'s2':18,'s3':24,}
internal1=pd.Series(internal1)
internal2={'s1':15,'s2':18,'s3':12,}
internal2=pd.Series(internal2)
internal2


s1    15
s2    18
s3    12
dtype: int64

In [6]:
final={'Internal1':internal1,'Internal2':internal2}
final=pd.DataFrame(final)
final

Internal1  Internal2
s1         21         15
s2         18         18
s3         24         12

In [8]:
final={'Internal1':internal1,'Internal2':internal2}
final=pd.DataFrame(final)
final['Internal1']

s1    21
s2    18
s3    24
Name: Internal1, dtype: int64

In [11]:
final.columns#Names of all coloumns


Index(['Internal1', 'Internal2'], dtype='object')

In [12]:
final.values#lists of all rows

array([[21, 15],
       [18, 18],
       [24, 12]], dtype=int64)

In [13]:
final.values[2,0]

24

In [14]:
final.values[2][0]

24

In [16]:
for row in final.values:
    print('Internal1-',row[0],', Internal2-',row[1])

Internal1- 21 , Internal2- 15
Internal1- 18 , Internal2- 18
Internal1- 24 , Internal2- 12


In [24]:
#adding another row to the table
final.loc['s3']=[20,18]
final

Internal1  Internal2
s1         21         15
s2         18         18
s3         20         18

In [25]:
#to remove
final=final.drop('s3')

In [26]:
final


Internal1  Internal2
s1         21         15
s2         18         18

In [29]:
#to change the values
final.values[1]=[12,24]
final

Internal1  Internal2
s1         21         15
s2         12         24

In [32]:
#Reading csv filedata
import pandas as pd
filepath='DataFiles/income.csv'
incomedf=pd.read_csv(filepath)
incomedf


GEOID       State   2005   2006   2007   2008   2009   2010   2011  \
0  04000US01     Alabama  37150  37952  42212  44476  39980  40933  42590   
1  04000US02      Alaska  55891  56418  62993  63989  61604  57848  57431   
2  04000US04     Arizona  45245  46657  47215  46914  45739  46896  48621   
3  04000US05    Arkansas  36658  37057  40795  39586  36538  38587  41302   
4  04000US06  California  51755  55319  55734  57014  56134  54283  53367   

    2012   2013  
0  43464  41381  
1  63648  61137  
2  47044  50602  
3  39018  39919  
4  57020  57528

In [2]:
#extract income of all states in 2013
#california:57528
incomedf.values

NameError: name 'incomedf' is not defined

In [34]:
#if we want the last row ie, last income values
for row in incomedf.values:
    print(row[1],':',row[-1])
    

Alabama : 41381
Alaska : 61137
Arizona : 50602
Arkansas : 39919
California : 57528


In [36]:
#if we want the average of Arizona state
sum=0
for i in range(2,11):
    sum+=incomedf.values[2][i]

sum/len(incomedf.values[2][2:])


47214.77777777778

In [1]:
#Average income of all states in year 2012
sum=0
for row in incomedf.values:
    print(row)
    sum+=row[-2]
sum/len(incomedf.values)

NameError: name 'incomedf' is not defined

In [1]:
incomedf=readCSVdata(filepath)
#function to print all coloumn names in a single line
#GEOID	State	2005	2006	2007	2008	2009	2010	2011	2012	2013
def printDataFrameColumns(df):
    columns=df.columns
    for column in coloumns:
        print(column,end=' ')
    return
printDataFrameColoumns(incomedf)

NameError: name 'readCSVdata' is not defined